#This is a simple template for a Dockerfile being used QBIC to build a container
FROM biocontainers/bowtie2 

LABEL \
  author="Alexander Peltzer" \
  description="Bowtie2 image for use QBIC" \
  maintainer="alexander.peltzer@qbic.uni-tuebingen.de"

ENV FASTQC_VERSION=2.3.0
