#This is a simple template for a Dockerfile being used QBIC to build a container
FROM biocontainers/fastqc 

LABEL \
  author="Alexander Peltzer" \
  description="FastQC image for use QBIC" \
  maintainer="alexander.peltzer@qbic.uni-tuebingen.de"

ENV FASTQC_VERSION=0.11.5
