FROM biocontainers/fastqc

LABEL \
  author="Alexander Peltzer" \
  description="FastQC image for use QBIC" \
  maintainer="alexander.peltzer@qbic.uni-tuebingen.de"

ENV FASTQC_VERSION=0.11.5

# Create QBIC directories 
RUN mkdir /lustre_cfc /lustre_qbic
